/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        btadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        btmin = new javax.swing.JButton();
        bttimes = new javax.swing.JButton();
        btdiv = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Bilangan 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 109, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Bilangan 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 147, -1, -1));

        bil1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(bil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 106, 166, -1));

        bil2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(bil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 144, 166, -1));

        btadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btadd.setText("+");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 175, 59, 69));

        hasil.setEditable(false);
        hasil.setColumns(20);
        hasil.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 262, 282, -1));

        btmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmin.setText("-");
        btmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btminActionPerformed(evt);
            }
        });
        getContentPane().add(btmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 175, 59, 69));

        bttimes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttimes.setText("*");
        bttimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttimesActionPerformed(evt);
            }
        });
        getContentPane().add(bttimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 175, 59, 69));

        btdiv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btdiv.setText("/");
        btdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdivActionPerformed(evt);
            }
        });
        getContentPane().add(btdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 175, 60, 69));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Kalkulator Sederhana");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 50, 150, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btminActionPerformed
    int b1= Integer.parseInt(bil1.getText());
    int b2= Integer.parseInt(bil2.getText());

    int hasilkurang = b1-b2;
    hasil.setText(String.valueOf(hasilkurang));
    // TODO add your handling code here:
    }//GEN-LAST:event_btminActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed

    int b1= Integer.parseInt(bil1.getText());
    int b2= Integer.parseInt(bil2.getText());
    
    int hasiltambah = b1+b2;
    hasil.setText(String.valueOf(hasiltambah));
// TODO add your handling code here:
    }//GEN-LAST:event_btaddActionPerformed

    private void bttimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimesActionPerformed
    int b1= Integer.parseInt(bil1.getText());
    int b2= Integer.parseInt(bil2.getText());

    int hasilkali = b1*b2;
    hasil.setText(String.valueOf(hasilkali));// TODO add your handling code here:
    }//GEN-LAST:event_bttimesActionPerformed

    private void btdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdivActionPerformed
    double b1= Double.parseDouble(bil1.getText());
    double b2= Double.parseDouble(bil2.getText());

    double hasilbagi = b1/b2;
    hasil.setText(String.valueOf(hasilbagi));
    // TODO add your handling code here:
    }//GEN-LAST:event_btdivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdiv;
    private javax.swing.JButton btmin;
    private javax.swing.JButton bttimes;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
